language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  # command to install dependencies
# script: python tests/test_all_of_the_units.py
# branches:
  # only:
    # - master
script: nosetests
